route:
  receiver: 'telegram-notifications'
  routes:
    - receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '7895863728:AAEFMjR1hdf0P9q83geCz6-Wl6lpJB__Vjw'
    chat_id: -1002435760497
    send_resolved: true
    parse_mode: 'HTML'