
#Create portainer.env file with the following content:
#HEIMDALL_PASS=<your password>

# to deploy: docker stack deploy -c portainer-stack.yml portainer
# to remove: docker stack rm portainer


version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - HEIMDALL_USER=admin
    env_file:
      - portainer.env
    ports:
      - 8080:80
      - 8043:443
    volumes:
      - heimdall_data:/config

networks:
  agent_network:


volumes:
  portainer_data:
  heimdall_data: