#docker compose -f docker-compose-ce.yaml up -d
#docker compose -f passbolt_/docker-compose-ce.yaml exec passbolt su -
# m -c "/usr/share/php/passbolt/bin/cake passbolt register_user -u dsb00715@gmail.com -f Deep -l Bhatt -r admin
# " -s /bin/sh www-data

# address=/rpi.local/192.168.0.123

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "3307:3306" # Use port 3307 on the host
    env_file:
      - db.env
    environment:
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
      # - letsencrypt
    env_file:
      - passbolt.env
    environment:
      APP_FULL_BASE_URL: https://192.168.0.123:8444
      # DATASOURCES_DEFAULT_HOST: "db"
      # DATASOURCES_DEFAULT_USERNAME: "passbolt"
      # DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      # DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      - ./certs:/etc/letsencrypt
    #command: [ "/usr/bin/wait-for.sh", "-t", "0", "db:3307", "--", "/docker-entrypoint.sh" ]
    ports:
      - 8005:80
      - 8444:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - ./certs:/etc/ssl/certs
  #     - ./certs:/etc/ssl/private
  #   ports:
  #     - "6080:80"
  #   command: certonly --standalone --email dsb00715@gmail.com --agree-tos --non-interactive --expand --domains dsb2425.duckdns.org -v

  # duckdns:
  #   image: maksimstojkovic/duckdns
  #   container_name: duckdns
  #   environment:
  #     - DUCKDNS_TOKEN=e75d021e-fc9f-4769-a3d4-b5978352edbc
  #     - DUCKDNS_DOMAIN=dsb2425.duckdns.org
  #     - DUCKDNS_DELAY=5 #optional
  #   restart: unless-stopped

  # letsencrypt:
  #   image: maksimstojkovic/letsencrypt
  #   container_name: letsencrypt
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #   environment:
  #     - DUCKDNS_TOKEN=e75d021e-fc9f-4769-a3d4-b5978352edbc
  #     - DUCKDNS_DOMAIN=dsb2425.duckdns.org
  #     - LETSENCRYPT_EMAIL= dsb00715@gmail.com
  #     - LETSENCRYPT_WILDCARD=true
  #     - LETSENCRYPT_DOMAINS=*.dsb2425.duckdns.org
  #     - TESTING=true
  #   restart: unless-stopped

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
