# stopping DNSmasq service:
# sudo systemctl stop dnsmasq
# sudo systemctl disable dnsmasq

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      # Map container ports to host ports
      # Expose port 53 on TCP and UDP for DNS queries
      - "53:53/tcp"
      - "53:53/udp"

      # Expose port 67 on UDP for DHCP server
      - "67:67/udp"

      # Expose port 68 on UDP for DHCP client
      - "1068:68/udp"

      # Expose port 80 on TCP for HTTP web interface
      - "8081:80/tcp"

      # Expose port 443 on TCP and UDP for HTTPS web interface
      - "8443:443/tcp"
      - "8443:443/udp"

      # Expose port 3000 on TCP for AdGuard Home's API
      - "2000:3000/tcp"

      # Expose port 853 on TCP for DNS-over-TLS (DoT)
      - "853:853/tcp"

      # Expose port 784 on UDP for DNS-over-QUIC (DoQ)
      - "784:784/udp"

      # Expose port 853 on UDP for DNS-over-DTLS (DoT)
      - "853:853/udp"

      # Expose port 8853 on UDP for DNS-over-TLS (DoT)
      - "8853:8853/udp"

      # Expose port 5443 on TCP and UDP for DNSCrypt
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
